version: '3.8'

services:
  db:
    image: postgres:17
    container_name: monew-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monew-app
    ports:
      - "8080:80"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
      - AWS_S3_SECRET_KEY=${AWS_S3_SECRET_KEY}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
    volumes:
      - binary-content:/app/storage
    depends_on:
      - db

    restart: always

volumes:
  postgres_data:
  binary-content: