spring:
  application:
    name: monew
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: ${MONGODB_URI}

naver:
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}
  api:
    url: https://openapi.naver.com/v1/search/news.xml

logging:
  s3:
    bucket: ${AWS_S3_BUCKET}

backup:
  s3:
    bucket: ${AWS_S3_BUCKET}