spring:
  application:
    name: monew
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update #none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

naver:
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}
  api:
    url: https://openapi.naver.com/v1/search/news.xml

logging:
  s3:
    bucket: ${bucket_name}

